package Back_End;

import java.io.Serializable;

/**
 * Store class
 * 
 * @author
 *
 */
public class Store implements Cities, Serializable {
	private static final long serialVersionUID = 1L;

	static int ID = 0;
	/**
	 * store name
	 */
	private final String Name;
	/**
	 * admin of store
	 */
	private StoreAdmin Admin;
	/**
	 * warehouse associated with store
	 */
	private Warehouse Warehouse;
	/**
	 * store id
	 */
	private int Id;
	/**
	 * city of store
	 */
	private String City;
	/**
	 * inventory of store
	 */
	private Inventory Inventory;
	/**
	 * revenue generated by store
	 */
	private double Revenue;

	/**
	 * constructor
	 * 
	 * @param name
	 * @param city
	 */
	public Store(String name, String city) {
		ID++;
		this.Name = name;
		this.setId(ID);
		this.setCity(city);
		this.setAdmin(null);
		this.setWarehouse(null);
		Inventory = new Inventory();
		System.out.println("---------------------");
		System.out.println("Store Created");
		System.out.println(this.toString());
	}

	/**
	 * get name of store
	 * 
	 * @return
	 */
	public String getName() {
		return Name;
	}

	/**
	 * get admin of store
	 * 
	 * @return
	 */
	public StoreAdmin getAdmin() {
		return Admin;
	}

	/**
	 * get id for admin
	 * 
	 * @return
	 */
	public int getId() {
		return Id;
	}

	/**
	 * get city of store
	 * 
	 * @return
	 */
	public String getCity() {
		return City;
	}

	/**
	 * get warehouse of store
	 * 
	 * @return
	 */
	public Warehouse getWarehouse() {
		return Warehouse;
	}

	/**
	 * set warehouse of store
	 * 
	 * @param Warehouse
	 */
	public void setWarehouse(Warehouse Warehouse) {
		this.Warehouse = Warehouse;
	}

	/**
	 * setadmin of store
	 * 
	 * @param Admin
	 */
	public void setAdmin(StoreAdmin Admin) {
		this.Admin = Admin;
	}

	/**
	 * set id of store
	 * 
	 * @param id
	 */
	public void setId(int id) {
		Id = id;
	}

	public String toString() {
		return "Id: " + this.Id + " , Name: " + this.getName() + " , City: " + this.getCity();
	}

	/**
	 * set city ofstore
	 * 
	 * @param city
	 */
	public void setCity(String city) {
		this.City = city;
	}

	/**
	 * get linked warehosue
	 */
	public void GetLinkedWarehouseDetails() {
		this.getWarehouse().GetWarehouseDetails();
	}

	/**
	 * get inventory
	 * 
	 * @return
	 */
	public Inventory getInventory() {
		return Inventory;
	}

	/**
	 * set inventory
	 * 
	 * @param inventory
	 */
	public void setInventory(Inventory inventory) {
		Inventory = inventory;
	}

	/**
	 * send message to warehouse for items to be ordered
	 * 
	 * @param message
	 */
	public void sendMessageToWarehouse(String message) {

		Warehouse.setAlertMessage(this.toString() + "\n" + message);
	}

	/**
	 * get revenue
	 * 
	 * @return
	 */
	public double getRevenue() {
		return Revenue;
	}

	/**
	 * set revenue
	 * 
	 * @param revenue
	 */
	public void setRevenue(double revenue) {
		Revenue += revenue;
	}

	/**
	 * get admin details
	 */
	public void GetAdminDetails() {
		System.out.println("------------------------------");
		System.out.println(this.getAdmin().toString());
	}

	/**
	 * gt store detaisl
	 */
	public void GetStoreDetails() {
		System.out.println("------------------------------");
		System.out.println(this.toString());
	}

	/**
	 * get city
	 */
	public String getCity(String City) {
		String C = null;
		for (String city : Cities) {
			if (city.equalsIgnoreCase(City)) {
				C = city;
				break;
			}
		}
		return C;
	}

	/**
	 * get distance
	 */
	public int getDistance(String City) {
		int D = 0;
		for (int i = 0; i < Cities.length; i++) {
			if (Cities[i].equalsIgnoreCase(City)) {
				D = i;
				break;
			}
		}
		return D;
	}

}
